### ISSUE TITLE
Does this project is abandoned?

### ISSUE THREAD

**Issue by emileber** [cofounders/backbone-session#2]
It leaves the impression to be abandoned and I'd really like to make improvements on it. I thought I could just fork and use my fork, or just start another repo with the same name as the new official repo, but then the npm and bower names are taken and it would be confusing a lot. 

So I thought that trying to reach the owner here could clear me up on the project status, or maybe if it was moved another place? Like on Gitlab? (but it seems abandoned there as well)

**Comment by sebdeckers** [comment]
@emileber Hi — Yes, I haven't used this project, nor Backbone, in what must be years. The GitLab repo is merely an automated import from my GitHub repos and no continued development has taken place. I'm not aware of anyone actually using this package. Happy to give you contributor access to GitHub/NPM. As long as you bump the major version I don't think there should be any risks.

**Comment by emileber** [comment]
I'd really like that.

**Comment by sebdeckers** [comment]
Great :) Do you have a PR?

**Comment by sebdeckers** [comment]
Thanks for #3 👍 I've added you as a maintainer of the package on NPM. Feel free to publish the changes. (Just do not remove me from the package. :) )
